# Generated by Django 4.0.6 on 2022-07-08 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='GALLERY/%y/%m/%d', verbose_name='Image in gallery')),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(350, message='The text is too long, it should be a maximum of 350 characters.')], verbose_name='Short image description')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
            },
        ),
    ]
