# Generated by Django 4.0.6 on 2022-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='show',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show this picture in the gallery images list?'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='galleryimage',
            order_with_respect_to='show',
        ),
    ]
