# Generated by Django 4.0.6 on 2022-07-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galleryimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='high',
            field=models.BooleanField(default=False, help_text='Any image with this value will automatically get more height in the gallery.', verbose_name='Should this picture be given more height in the gallery?'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='wide',
            field=models.BooleanField(default=False, help_text='Any image with this value will automatically get more width in the gallery.', verbose_name='Should this picture be given more width in the gallery?'),
        ),
    ]
