# Generated by Django 4.0.6 on 2022-07-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_design_galleryimage_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(blank=True, max_length=185),
        ),
        migrations.AlterField(
            model_name='design',
            name='title_en',
            field=models.CharField(blank=True, max_length=185, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='title_he',
            field=models.CharField(blank=True, max_length=185, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='title_ru',
            field=models.CharField(blank=True, max_length=185, null=True),
        ),
    ]
